Upgrade to the new analyzer to makes pub bots happy.
I see the following errors locally.
But it does not seem to be analyzer related.

ERROR: The argument type '(String) → void' cannot be assigned to the parameter type 'Parser(dynamic) → String'. ([linter] tool/grind.dart:15)
ERROR: The argument type '(String) → void' cannot be assigned to the parameter type 'Parser(dynamic) → String'. ([linter] tool/grind.dart:21)

R=brianwilkerson@google.com, pquitslund@google.com
BUG=

Review URL: https://codereview.chromium.org//2239073006 .